import { test, expect } from '@playwright/test';
test('keyboard regions, modal focus containment and restoration',async({page})=>{
  await page.goto('/');
  await expect(page.getByRole('button',{name:'Report cursor and indentation'})).toBeEnabled();
  await page.keyboard.press('F6');
  await expect(page.locator('#workbench-navigation')).toBeFocused();
  await page.keyboard.press('F6');
  await expect(page.locator('#explorer')).toBeFocused();
  await page.keyboard.press('F6');
  await expect(page.locator('.monaco-editor textarea')).toBeFocused();
  await page.keyboard.press('F6');
  await expect(page.locator('#terminal')).toBeFocused();
  await page.keyboard.press('Shift+F6');
  await expect(page.locator('.monaco-editor textarea')).toBeFocused();
  const opener=page.getByRole('button',{name:'Commands ⌘⇧P'});
  await opener.click();
  const dialog=page.getByRole('dialog',{name:'Commands'});
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('textbox',{name:'Search commands'})).toBeFocused();
  await dialog.getByRole('button',{name:'Close commands'}).focus();
  await page.keyboard.press('Tab');
  await expect(dialog.getByRole('textbox',{name:'Search commands'})).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(dialog.getByRole('button',{name:'Close commands'})).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(opener).toBeFocused();
  await opener.click();
  await dialog.getByRole('textbox').fill('focus explorer');
  await page.keyboard.press('Enter');
  await expect(page.locator('#explorer')).toBeFocused();
});
test('accessibility preferences persist and 200% zoom stays usable',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByLabel('Whole-app zoom').selectOption('200');
  await page.getByLabel('Workbench contrast').selectOption('light');
  await page.getByLabel('Screen-reader support').selectOption('on');
  await page.getByLabel('Reduce motion',{exact:true}).check();
  await page.getByLabel('Large editor and terminal cursor').check();
  await page.reload();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await expect(page.getByLabel('Whole-app zoom')).toHaveValue('200');
  await expect(page.getByLabel('Workbench contrast')).toHaveValue('light');
  await expect(page.getByLabel('Reduce motion',{exact:true})).toBeChecked();
  const bounds=await page.locator('.app-container').boundingBox();
  expect(Math.abs(bounds!.width-1280)).toBeLessThan(2);
  expect(Math.abs(bounds!.height-900)).toBeLessThan(2);
  await page.getByRole('button',{name:'Commands ⌘⇧P'}).click();
  const zoomedDialog=page.getByRole('dialog',{name:'Commands'});
  const dialogBounds=await zoomedDialog.boundingBox();
  expect(dialogBounds!.x).toBeGreaterThanOrEqual(0);
  expect(dialogBounds!.x+dialogBounds!.width).toBeLessThanOrEqual(1281);
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:800,height:600});
  const settingsBounds=await page.locator('.workbench-page:visible').boundingBox();
  expect(settingsBounds!.height).toBeGreaterThan(50);
  await page.getByRole('button',{name:'Reset accessibility settings'}).click();
  await expect(page.getByLabel('Whole-app zoom')).toHaveValue('100');
  await expect(page.getByLabel('Optional sound cues')).not.toBeChecked();
});
test('screen reader editor mode permits Tab to leave and reports position',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('accessibility.v1',JSON.stringify(JSON.stringify({screenReader:'on'}))));
  await page.goto('/');
  await expect(page.getByRole('button',{name:'Report cursor and indentation'})).toBeEnabled();
  await page.getByRole('button',{name:'Report cursor and indentation'}).click();
  await expect(page.locator('.editor-navigation [role=status]')).toContainText('Line 1, column 1. Indentation: 0 spaces, 0 tabs.');
  await page.keyboard.press('F6');
  await page.keyboard.press('Shift+F6');
  await expect(page.locator('.monaco-editor textarea')).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(page.locator('.monaco-editor textarea')).not.toBeFocused();
});
test('terminal snapshot remains readable after shell startup failure',async({page})=>{
  await page.goto('/tests/fixtures/accessibility.html?fixture=terminal');
  await expect(page.getByRole('status')).toContainText('Could not start shell');
  await page.getByRole('button',{name:'Review recent output'}).click();
  const snapshot=page.getByRole('textbox',{name:'Terminal output snapshot'});
  await expect(snapshot).toBeFocused();
  await expect(snapshot).toContainText('could not start shell');
  await page.getByRole('button',{name:'Go to end',exact:true}).click();
  expect(await snapshot.evaluate((node:HTMLTextAreaElement)=>node.selectionStart===node.value.length)).toBe(true);
  await page.getByRole('button',{name:'Close snapshot and return to shell'}).click();
  await expect(snapshot).toHaveCount(0);
  await expect(page.locator('.xterm-helper-textarea')).toBeFocused();
});
test('agent proposal focuses review and exposes removed then added text',async({page})=>{
  await page.goto('/tests/fixtures/accessibility.html?fixture=agent');
  await page.getByLabel('Goal',{exact:true}).fill('Update the example');
  await page.getByRole('button',{name:'Start agent run'}).click();
  await expect(page.getByRole('heading',{name:'Review edit_file'})).toBeFocused();
  await page.getByRole('button',{name:'Read removed text'}).click();
  await expect(page.getByRole('heading',{name:'Removed text'})).toBeFocused();
  await expect(page.getByLabel('Removed text',{exact:true})).toHaveText('const value = 1;');
  await page.getByRole('button',{name:'Read added text'}).click();
  await expect(page.getByRole('heading',{name:'Added text'})).toBeFocused();
  await expect(page.getByLabel('Added text',{exact:true})).toHaveText('const value = 2;');
  await page.getByRole('button',{name:'Reject and stop'}).click();
  await expect(page.getByRole('status')).toContainText('Stopped');
});
