import {useState} from 'react';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {appleMetadata,appleDestinations,type AppleMetadata,type AppleSelection,type AppleDestination} from './appleDevelopment';
type Tool={name:string;available:boolean;detail:string};
export default function ApplePanel({root}:{root:string}){
 const [tools,setTools]=useState<Tool[]>([]),[projects,setProjects]=useState<string[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const [selection,setSelection]=useState<AppleSelection>({project:'',scheme:'',target:'',configuration:'Debug',destination:''}),[metadata,setMetadata]=useState<AppleMetadata>({schemes:[],targets:[],configurations:[]}),[destinations,setDestinations]=useState<AppleDestination[]>([]),[trusted,setTrusted]=useState(false);
 const change=(patch:Partial<AppleSelection>)=>{setSelection(s=>({...s,...patch}));setTrusted(false);};
 async function load(kind:'metadata'|'destinations'){setBusy(true);setStatus('Reading '+kind+'…');try{const text=await invoke<string>('apple_query',{root,query:{kind,...selection}});if(kind==='metadata'){const result=appleMetadata(text);setMetadata(result);setSelection(s=>({...s,scheme:result.schemes[0]??'',target:'',configuration:result.configurations.includes('Debug')?'Debug':result.configurations[0]??'Debug',destination:''}));setDestinations([]);}else setDestinations(appleDestinations(text));setStatus('Loaded '+kind);}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 async function inspect(){setBusy(true);setStatus('Checking Apple toolchain…');try{setTools(await invoke<Tool[]>('apple_toolchain'));if(root)setProjects(await invoke<string[]>('apple_projects',{root}));setStatus('Toolchain checked. Project discovery searches five directory levels.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 return <section className="workbench-page"><h1>Apple development</h1><p>Develop Swift packages and iOS/macOS projects using your selected Xcode installation.</p><button disabled={!isTauri()||busy} onClick={()=>void inspect()}>Check Xcode and discover projects</button><p role="status">{status}</p>{tools.map(tool=><details key={tool.name}><summary>{tool.name}: {tool.available?'available':'unavailable'}</summary><pre>{tool.detail}</pre></details>)}<h2>Project and destination</h2>
 <label>Apple project<select disabled={busy} value={selection.project} onChange={e=>{change({project:e.target.value,scheme:'',target:'',destination:''});setMetadata({schemes:[],targets:[],configurations:[]});setDestinations([]);}}><option value="">Choose a discovered project</option>{projects.map(path=><option key={path}>{path}</option>)}</select></label>
 <label className="check"><input type="checkbox" checked={trusted} disabled={busy} onChange={e=>setTrusted(e.target.checked)}/> Trust this project’s Apple tool commands</label><p>Metadata queries may resolve packages and load project build configuration. Commands run only when requested.</p>
 <button disabled={busy||!trusted||!selection.project} onClick={()=>void load('metadata')}>Load schemes and targets</button>
 <label>Scheme<select disabled={busy} value={selection.scheme} onChange={e=>change({scheme:e.target.value,target:'',destination:''})}><option value="">Use a target instead</option>{metadata.schemes.map(name=><option key={name}>{name}</option>)}</select></label>
 <label>Target<select disabled={busy||selection.project.endsWith('.xcworkspace')} value={selection.target} onChange={e=>change({target:e.target.value,scheme:'',destination:''})}><option value="">Use the selected scheme</option>{metadata.targets.map(name=><option key={name}>{name}</option>)}</select></label>
 <label>Build configuration<input disabled={busy} value={selection.configuration} list="apple-configurations" onChange={e=>change({configuration:e.target.value})}/><datalist id="apple-configurations">{metadata.configurations.map(name=><option key={name} value={name}/>)}</datalist></label>
 <button disabled={busy||!trusted||!selection.scheme||selection.project.endsWith('Package.swift')} onClick={()=>void load('destinations')}>Load destinations</button>
 <label>Destination<select disabled={busy} value={selection.destination} onChange={e=>change({destination:e.target.value})}><option value="">Toolchain default</option>{destinations.map(d=><option key={d.platform+d.id} disabled={!d.available} value={d.id.startsWith('dvtdevice-')?'generic/platform='+d.platform:'platform='+d.platform+',id='+d.id}>{d.name} · {d.platform}{!d.available?' (unavailable)':''}</option>)}</select></label>
 </section>;
}
