import type {DebugConfig} from './debugging';
import {listen} from '@tauri-apps/api/event';
import OutputLog from './OutputLog';
import type {Task} from './workflows';
import type {InfrastructureDiagnostic} from './infrastructure';
import {useEffect,useRef,useState} from 'react';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {buildServerPlan,defaultSigning,archivePlan,exportPlan,exportOptions,exportMethods,type AppleSigning,appleDebug,appleDevices,deviceAction,type AppleDevice,appleSimulators,simulatorAction,appleProducts,type AppleSimulator,type AppleProduct,appleBuild,appleDiagnostics,appleMetadata,appleDestinations,type AppleMetadata,type AppleSelection,type AppleDestination} from './appleDevelopment';
type Tool={name:string;available:boolean;detail:string};
export default function ApplePanel({root,dirty,onOpen,onProblems,onDebug,active,onLanguage}:{active:string;onLanguage:(project:string)=>void;onDebug:(config:DebugConfig)=>void;root:string;dirty:boolean;onOpen:(path:string,line:number)=>void;onProblems:(problems:InfrastructureDiagnostic[])=>void}){
 const [tools,setTools]=useState<Tool[]>([]),[projects,setProjects]=useState<string[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const [selection,setSelection]=useState<AppleSelection>({project:'',scheme:'',target:'',configuration:'Debug',destination:''}),[metadata,setMetadata]=useState<AppleMetadata>({schemes:[],targets:[],configurations:[]}),[destinations,setDestinations]=useState<AppleDestination[]>([]),[trusted,setTrusted]=useState(false);
 const change=(patch:Partial<AppleSelection>)=>{setSelection(s=>({...s,...patch}));setTrusted(false);setPlan(null);};
 const [plan,setPlan]=useState<{tasks:Task[];result?:string}|null>(null),[output,setOutput]=useState(''),[problems,setProblems]=useState<InfrastructureDiagnostic[]>([]),[resultPath,setResultPath]=useState(''),[summary,setSummary]=useState('');
 const [simulators,setSimulators]=useState<AppleSimulator[]>([]),[simulator,setSimulator]=useState(''),[appPath,setAppPath]=useState(''),[bundle,setBundle]=useState(''),[products,setProducts]=useState<AppleProduct[]>([]);
 async function loadSimulators(){setBusy(true);try{setSimulators(appleSimulators(await invoke<string>('apple_query',{root,query:{kind:'simulators'}})));setStatus('Simulator list refreshed.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 async function loadProducts(){setBusy(true);try{setProducts(appleProducts(await invoke<string>('apple_query',{root,query:{kind:'settings',...selection}}),root));setStatus('Product settings loaded.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 function prepareSimulator(action:'boot'|'shutdown'|'install'|'launch'){try{setPlan({tasks:simulatorAction(simulator,action,appPath,bundle)});setStatus('Review simulator commands before running.');}catch(e){setStatus(String(e));}}
 const [executable,setExecutable]=useState(''),[pid,setPid]=useState('');
 const [devices,setDevices]=useState<AppleDevice[]>([]),[device,setDevice]=useState('');
 async function loadDevices(){setBusy(true);try{const found=appleDevices(await invoke<string>('apple_query',{root,query:{kind:'devices'}}));setDevices(found);if(!found.some(d=>d.id===device))setDevice('');setStatus(found.length?'Device list refreshed.':'No connected devices. Pair and enable Developer Mode using Xcode.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 function prepareDevice(action:'install'|'launch'|'console'){try{setPlan({tasks:deviceAction(device,action,appPath,bundle)});setStatus('Review device commands before running.');}catch(e){setStatus(String(e));}}
 const [signing,setSigning]=useState<AppleSigning>(defaultSigning),[archive,setArchive]=useState('.afteredit/apple/archives/App.xcarchive'),[exportPath,setExportPath]=useState('.afteredit/apple/export'),[optionsPath,setOptionsPath]=useState('ExportOptions.plist'),[method,setMethod]=useState('debugging'),[profiles,setProfiles]=useState('{}'),[plist,setPlist]=useState('');
 const changeSigning=(patch:Partial<AppleSigning>)=>{setSigning(s=>({...s,...patch}));setPlan(null);setPlist('');};
 function prepareArchive(){try{setPlan(archivePlan(selection,signing,archive));setStatus('Review archive commands. Existing archive paths may be replaced by Xcode.');}catch(e){setStatus(String(e));}}
 function prepareExport(){try{setPlan(exportPlan(archive,optionsPath,exportPath,signing.allowUpdates));setStatus('Review export commands and the selected plist.');}catch(e){setStatus(String(e));}}
 async function saveOptions(){try{const path=await invoke<string|null>('save_as',{content:plist});if(path?.startsWith(root+'/')){setOptionsPath(path.slice(root.length+1));setPlan(null);setStatus('Export options saved.');}else if(path)setStatus('Saved outside the project. Save a copy inside the project to use it here.');}catch(e){setStatus(String(e));}}
 async function openXcode(path:string){setBusy(true);try{await invoke('apple_open',{root,path,project:selection.project,line:1});setStatus('Opened in Xcode.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 const running=useRef(false),cancelled=useRef(false);
 useEffect(()=>()=>{cancelled.current=true;},[]);
 function prepare(action:'build'|'test'){try{setPlan(appleBuild(selection,action,Date.now().toString(36),signing));setStatus('Review the commands, then run.');}catch(e){setStatus(String(e));}}
 async function execute(){if(!plan||running.current)return;running.current=true;cancelled.current=false;setBusy(true);setOutput('');setSummary('');setResultPath('');setProblems([]);onProblems([]);let off=()=>{},combined='';try{
  off=await listen<{text:string}>('task:output',e=>{if(running.current)setOutput(v=>(v+e.payload.text).slice(-200000));});
  for(const task of plan.tasks){if(cancelled.current)break;const result=await invoke<{code:number;output:string}>('run_task',{root,cwd:task.cwd??'.',task});combined+=result.output;const found=appleDiagnostics(result.output,root,task.cwd??'.');setProblems(v=>[...v,...found]);onProblems(appleDiagnostics(combined,root,task.cwd??'.'));if(result.code!==0)throw new Error('Apple command exited '+result.code+'. See output.');}
  if(cancelled.current)setStatus('Apple action stopped.');else{setResultPath(plan.result??'');setStatus('Apple action completed.');}
 }catch(e){if(plan.result)setResultPath(plan.result);setStatus(String(e));}finally{off();running.current=false;setBusy(false);setOutput(previous=>combined||previous||'No command output captured.');}}
 async function readResult(){setBusy(true);try{setSummary(await invoke<string>('apple_query',{root,query:{kind:'results',path:resultPath}}));setStatus('Test results loaded.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 async function load(kind:'metadata'|'destinations'){setBusy(true);setStatus('Reading '+kind+'…');try{const text=await invoke<string>('apple_query',{root,query:{kind,...selection}});if(kind==='metadata'){const result=appleMetadata(text);setMetadata(result);setSelection(s=>({...s,scheme:result.schemes[0]??'',target:'',configuration:result.configurations.includes('Debug')?'Debug':result.configurations[0]??'Debug',destination:''}));setDestinations([]);}else setDestinations(appleDestinations(text));setStatus('Loaded '+kind);}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 async function inspect(){setBusy(true);setStatus('Checking Apple toolchain…');try{setTools(await invoke<Tool[]>('apple_toolchain'));if(root)setProjects(await invoke<string[]>('apple_projects',{root}));setStatus('Toolchain checked. Project discovery searches five directory levels.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 return <section className="workbench-page"><h1>Apple development</h1><p>Develop Swift packages and iOS/macOS projects using your selected Xcode installation.</p><button disabled={!isTauri()||busy} onClick={()=>void inspect()}>Check Xcode and discover projects</button><p role="status">{status}</p>{tools.map(tool=><details key={tool.name}><summary>{tool.name}: {tool.available?'available':'unavailable'}</summary><pre>{tool.detail}</pre></details>)}<h2>Project and destination</h2>
 <label>Apple project<select disabled={busy} value={selection.project} onChange={e=>{change({project:e.target.value,scheme:'',target:'',destination:''});setMetadata({schemes:[],targets:[],configurations:[]});setDestinations([]);}}><option value="">Choose a discovered project</option>{projects.map(path=><option key={path}>{path}</option>)}</select></label>
 <label className="check"><input type="checkbox" checked={trusted} disabled={busy} onChange={e=>setTrusted(e.target.checked)}/> Trust this project’s Apple tool commands</label><p>Metadata queries may resolve packages and load project build configuration. Commands run only when requested.</p>
 <button disabled={busy||!trusted||!selection.project} onClick={()=>void load('metadata')}>Load schemes and targets</button>
 <label>Scheme<select disabled={busy} value={selection.scheme} onChange={e=>change({scheme:e.target.value,target:'',destination:''})}><option value="">Use a target instead</option>{metadata.schemes.map(name=><option key={name}>{name}</option>)}</select></label>
 <label>Target<select disabled={busy||selection.project.endsWith('.xcworkspace')} value={selection.target} onChange={e=>change({target:e.target.value,scheme:'',destination:''})}><option value="">Use the selected scheme</option>{metadata.targets.map(name=><option key={name}>{name}</option>)}</select></label>
 <label>Build configuration<input disabled={busy} value={selection.configuration} list="apple-configurations" onChange={e=>change({configuration:e.target.value})}/><datalist id="apple-configurations">{metadata.configurations.map(name=><option key={name} value={name}/>)}</datalist></label>
 <button disabled={busy||!trusted||!selection.scheme||selection.project.endsWith('Package.swift')} onClick={()=>void load('destinations')}>Load destinations</button>
 <label>Destination<select disabled={busy} value={selection.destination} onChange={e=>change({destination:e.target.value})}><option value="">Toolchain default</option>{destinations.map(d=><option key={d.platform+d.id} disabled={!d.available} value={d.id.startsWith('dvtdevice-')?'generic/platform='+d.platform:'platform='+d.platform+',id='+d.id}>{d.name} · {d.platform}{!d.available?' (unavailable)':''}</option>)}</select></label>
 <h2>Built products</h2><button disabled={busy||!trusted||!selection.project||selection.project.endsWith('Package.swift')} onClick={()=>void loadProducts()}>Read product settings</button>
 {products.map((product,i)=><button key={i} disabled={busy||!product.app.endsWith('.app')} onClick={()=>{setAppPath(product.app);setBundle(product.bundle);setExecutable(product.executable);setPlan(null);}}>Use {product.name}: {product.app||'output outside project'}</button>)}
 <label>Built app path relative to project<input disabled={busy} value={appPath} onChange={e=>{setAppPath(e.target.value);setPlan(null);}}/></label><label>App bundle identifier<input disabled={busy} value={bundle} onChange={e=>{setBundle(e.target.value);setPlan(null);}}/></label>
 <h2>Simulators</h2><button disabled={busy||!root||!isTauri()} onClick={()=>void loadSimulators()}>Refresh simulators</button>
 <label>Simulator<select disabled={busy} value={simulator} onChange={e=>{setSimulator(e.target.value);setPlan(null);}}><option value="">Choose a simulator</option>{simulators.map(device=><option key={device.id} value={device.id} disabled={!device.available}>{device.name} · {device.runtime} · {device.state}{!device.available?' (unavailable)':''}</option>)}</select></label>
 {(['boot','shutdown','install','launch'] as const).map(action=><button key={action} disabled={busy||!trusted||!simulator} onClick={()=>prepareSimulator(action)}>Prepare simulator {action}</button>)}
 <h2>Connected devices</h2><p>Device apps must be signed for the selected device. Pair the device and enable Developer Mode in Xcode first.</p><button disabled={busy||!root||!isTauri()} onClick={()=>void loadDevices()}>Refresh connected devices</button>
 <label>Connected device<select disabled={busy} value={device} onChange={e=>{setDevice(e.target.value);setPlan(null);}}><option value="">Choose a connected device</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name} · {d.model} · Developer Mode {d.developerMode}</option>)}</select></label>
 {(['install','launch','console'] as const).map(action=><button key={action} disabled={busy||!trusted||!device} onClick={()=>prepareDevice(action)}>Prepare device {action}</button>)}
 <h2>Swift and app debugging</h2><p>Launch local macOS/Swift executables directly. For a simulator app, launch it in the selected simulator, then attach using the PID printed by simctl. Device attach requires a signed debug build and Developer Mode.</p>
 <label>Debug executable relative to project<input disabled={busy} value={executable} onChange={e=>setExecutable(e.target.value)}/></label><label>Running app process ID<input disabled={busy} value={pid} onChange={e=>setPid(e.target.value)} inputMode="numeric"/></label>
 {(['launch','attach','device'] as const).map(mode=><button key={mode} disabled={busy||dirty||!root||!executable||(mode==='device'&&!device)} onClick={()=>{try{onDebug(appleDebug(root,executable,mode,pid,device));}catch(e){setStatus(String(e));}}}>Configure {mode==='launch'?'Swift/macOS launch':mode==='attach'?'local or simulator attach':'device attach'}</button>)}
 <h2>Signing and distribution</h2><p>Use Xcode to manage accounts, certificates, capabilities and device registration. Archive and export commands use those installed credentials. Select a new output path to preserve earlier artifacts.</p>
 <label>Signing style<select disabled={busy} value={signing.style} onChange={e=>changeSigning({style:e.target.value as AppleSigning['style']})}><option value="project">Project settings</option><option value="automatic">Automatic</option><option value="manual">Manual</option><option value="unsigned">Unsigned build only</option></select></label>
 <label>Development team ID<input disabled={busy} value={signing.team} onChange={e=>changeSigning({team:e.target.value})}/></label><label>Provisioning profile name or UUID<input disabled={busy} value={signing.profile} onChange={e=>changeSigning({profile:e.target.value})}/></label><label>Signing certificate name or SHA-1<input disabled={busy} value={signing.identity} onChange={e=>changeSigning({identity:e.target.value})}/></label>
 <label className="check"><input type="checkbox" disabled={busy} checked={signing.allowUpdates} onChange={e=>changeSigning({allowUpdates:e.target.checked})}/> Allow Xcode to update provisioning profiles and contact Apple</label>
 <label>Archive path relative to project<input disabled={busy} value={archive} onChange={e=>{setArchive(e.target.value);setPlan(null);}}/></label><button disabled={busy||!trusted||dirty} onClick={prepareArchive}>Prepare archive</button>
 <label>Export method<select disabled={busy} value={method} onChange={e=>{setMethod(e.target.value);setPlist('');}}>{exportMethods.map(m=><option key={m}>{m}</option>)}</select></label>
 <label>Export provisioning profiles JSON (bundle ID to profile)<textarea disabled={busy} value={profiles} onChange={e=>{setProfiles(e.target.value);setPlist('');}}/></label>
 <button disabled={busy} onClick={()=>{try{const mapping=JSON.parse(profiles);if(!mapping||Array.isArray(mapping)||typeof mapping!=='object')throw new Error('Profiles must be a JSON object.');setPlist(exportOptions(method,signing,mapping));}catch(e){setStatus(String(e));}}}>Generate export options</button>{plist&&<><pre tabIndex={0} aria-label="Generated export options">{plist}</pre><button disabled={busy||!isTauri()} onClick={()=>void saveOptions()}>Save export options as new file</button></>}
 <label>Export options plist relative to project<input disabled={busy} value={optionsPath} onChange={e=>{setOptionsPath(e.target.value);setPlan(null);}}/></label><label>Export directory relative to project<input disabled={busy} value={exportPath} onChange={e=>{setExportPath(e.target.value);setPlan(null);}}/></label><button disabled={busy||!trusted||dirty} onClick={prepareExport}>Prepare export</button>
 <h2>Xcode editors and language context</h2><p>SwiftUI Canvas previews, storyboards, XIBs, asset catalogs, signing capabilities and account management open in Xcode. Save edits before opening the same file there.</p>
 <button disabled={busy||!selection.project||dirty} onClick={()=>void openXcode(selection.project)}>Open project in Xcode</button>
 <button disabled={busy||!selection.project||dirty||!active.startsWith(root+'/')} onClick={()=>void openXcode(active.slice(root.length+1))}>Open current file for previews or Interface Builder</button>
 <button disabled={busy} onClick={()=>onLanguage(selection.project)}>Configure SourceKit-LSP</button>
 <p>Swift packages need no extra build server. For Xcode projects, install xcode-build-server separately. Its configuration command creates or updates buildServer.json in the selected project root. Build in Xcode to populate its build settings, then connect SourceKit-LSP at that same root.</p>
 <button disabled={busy||!trusted||!selection.scheme} onClick={()=>{try{setPlan(buildServerPlan(selection));setStatus('Review the build-server configuration command.');}catch(e){setStatus(String(e));}}}>Prepare Xcode build-server configuration</button>
 <h2>Build and test</h2><p>Builds and tests can execute project scripts and package plugins. Save modified files first.</p>
 <button disabled={busy||!trusted||!selection.project||dirty} onClick={()=>prepare('build')}>Prepare build</button><button disabled={busy||!trusted||!selection.project||dirty} onClick={()=>prepare('test')}>Prepare tests</button>
 {dirty&&<p>Save modified project files before running Apple commands.</p>}
 {plan&&<section aria-label="Apple command review"><h3>Command review</h3><pre tabIndex={0}>{JSON.stringify(plan.tasks,null,2)}</pre><button disabled={busy||!trusted||dirty||!isTauri()} onClick={()=>void execute()}>Run reviewed Apple commands</button></section>}
 {busy&&running.current&&<button onClick={()=>{cancelled.current=true;void invoke('cancel_task').catch(e=>setStatus(String(e)));}}>Stop Apple action</button>}
 <h2>Build problems</h2>{problems.map((problem,i)=><button key={i} onClick={()=>onOpen(problem.path,problem.line)}>{problem.severity}: {problem.path}:{problem.line} — {problem.message}</button>)}
 <OutputLog label="Apple command output">{output||'Build and test output appears here.'}</OutputLog>
 {resultPath&&<section><h2>Result bundle</h2><p>{resultPath}</p><button disabled={busy} onClick={()=>void readResult()}>Read test results</button>{summary&&<pre tabIndex={0} aria-label="Apple test results">{summary}</pre>}</section>}
 </section>;
}
