import OutputLog from './OutputLog';
import {useEffect,useState} from 'react';
import {isTauri} from '@tauri-apps/api/core';
import {debugPresets,type DebugConfig} from './debugging';
import type {useDebugger} from './useDebugger';
type Debugger=ReturnType<typeof useDebugger>;
function VariableTree({reference,debug,depth=0}:{reference:number;debug:Debugger;depth?:number}){
 const [edit,setEdit]=useState<{name:string;value:string}|null>(null);
 return <div className="debug-variables"><button onClick={()=>void debug.loadVariables(reference).catch(debug.report)}>Load / refresh values</button>{(debug.variables[reference]??[]).map((v,i)=><div key={i}><span>{v.name}: <code>{v.value}</code> {v.type&&<small>({v.type})</small>}</span>{debug.caps.supportsSetVariable&&<button onClick={()=>setEdit({name:v.name,value:v.value})}>Edit</button>}{v.variablesReference>0&&depth<8&&<details><summary>Expand {v.name}</summary><VariableTree reference={v.variablesReference} debug={debug} depth={depth+1}/></details>}</div>)}{edit&&<form onSubmit={e=>{e.preventDefault();void debug.setVariable(reference,edit.name,edit.value).then(()=>setEdit(null)).catch(debug.report);}}><label>New value for {edit.name}<input value={edit.value} onChange={e=>setEdit({...edit,value:e.target.value})}/></label><button>Apply value</button><button type="button" onClick={()=>setEdit(null)}>Cancel</button></form>}</div>;
}
export default function DebugPanel({debug,active,dirty,configured}:{debug:Debugger;active:string;dirty:boolean;configured:Record<string,DebugConfig>}){
 const [text,setText]=useState(JSON.stringify(debugPresets['macOS Xcode LLDB'],null,2)),[trusted,setTrusted]=useState(false),[line,setLine]=useState(1),[condition,setCondition]=useState(''),[hit,setHit]=useState(''),[log,setLog]=useState(''),[filters,setFilters]=useState(''),[expression,setExpression]=useState(''),[watch,setWatch]=useState('');
 const configurations={...debugPresets,...configured};
 useEffect(()=>{try{setText(localStorage.getItem('debug.config:'+debug.root)??JSON.stringify(debugPresets['macOS Xcode LLDB'],null,2));}catch{}setTrusted(false);},[debug.root]);
 useEffect(()=>{if(watch&&debug.phase==='paused'&&debug.frame)void debug.evaluate(watch).catch(debug.report);},[watch,debug.frame,debug.phase]);
 const activeSession=!['idle','ended'].includes(debug.phase);
 const call=(fn:()=>Promise<unknown>)=>void fn().catch(debug.report);
 return <aside className="debug-panel workbench-page"><h2>Run and debug · {debug.phase}</h2><p role="status">{debug.stopReason}</p><p role="alert">{debug.error}</p>
 <div><button disabled={!isTauri()||!debug.root||!trusted||activeSession||debug.busy||dirty} onClick={()=>call(()=>debug.start(text,filters.split(',').map(v=>v.trim()).filter(Boolean)))}>Start</button><button disabled={debug.phase==='idle'} onClick={()=>call(debug.stop)}>Stop / disconnect</button></div>
 {dirty&&<p>Save modified project files before starting: the debugger executes files on disk.</p>}
 <details open={!activeSession}><summary>Launch / attach configuration</summary><select aria-label="Debug configuration preset" disabled={activeSession} onChange={e=>{setText(JSON.stringify(configurations[e.target.value],null,2));setTrusted(false);}} defaultValue=""><option value="" disabled>Select a preset or project configuration…</option>{Object.keys(configurations).map(n=><option key={n}>{n}</option>)}</select><textarea aria-label="Debug configuration JSON" rows={12} value={text} disabled={activeSession} onChange={e=>{setText(e.target.value);setTrusted(false);}}/><button disabled={activeSession} onClick={()=>{try{JSON.parse(text);localStorage.setItem('debug.config:'+debug.root,text);}catch(e){debug.report(e);}}}>Save local configuration</button><label className="check"><input type="checkbox" checked={trusted} disabled={activeSession} onChange={e=>setTrusted(e.target.checked)}/> Trust and run this adapter and target</label><p>Install adapters separately. TCP connects to an already-running localhost adapter. Use internalConsole; terminal reverse requests are unsupported.</p><label>Exception filter IDs (comma separated)<input value={filters} disabled={activeSession} onChange={e=>setFilters(e.target.value)}/></label></details>
 {debug.caps.exceptionBreakpointFilters?.length>0&&<p>Available exception filters: {debug.caps.exceptionBreakpointFilters.map((f:any)=>`${f.filter}: ${f.label}`).join(' · ')}. Set filters before the next launch.</p>}
 <div className="debug-controls">{[['continue','Continue'],['pause','Pause'],['next','Step over'],['stepIn','Step into'],['stepOut','Step out']].map(([id,label])=><button key={id} disabled={debug.busy||debug.thread===undefined||(id==='pause'?debug.phase!=='running':debug.phase!=='paused')} onClick={()=>call(()=>debug.control(id))}>{label}</button>)}</div>
 <details open><summary>Breakpoints</summary><p>Click the editor gutter or add a line below. Hollow markers are unverified.</p><div className="field-row"><input aria-label="Breakpoint line" type="number" min="1" value={line} onChange={e=>setLine(Number(e.target.value))}/><button disabled={!active.startsWith(debug.root+'/')||!debug.root||!Number.isInteger(line)||line<1||debug.busy} onClick={()=>call(()=>debug.changePoints([...debug.points.filter(p=>p.path!==active||p.line!==line),{path:active,line,condition:condition||undefined,hitCondition:hit||undefined,logMessage:log||undefined}]))}>Add / replace</button></div><input aria-label="Breakpoint condition" placeholder="Condition (optional)" value={condition} onChange={e=>setCondition(e.target.value)}/><input aria-label="Hit count condition" placeholder="Hit count (optional)" value={hit} onChange={e=>setHit(e.target.value)}/><input aria-label="Logpoint message" placeholder="Logpoint message (optional)" value={log} onChange={e=>setLog(e.target.value)}/>{debug.points.filter(p=>p.path.startsWith(debug.root+'/')).map(p=><div key={p.path+':'+p.line}><label className="check"><input type="checkbox" checked={p.enabled!==false} disabled={debug.busy} onChange={e=>call(()=>debug.changePoints(debug.points.map(b=>b===p?{...b,enabled:e.target.checked}:b)))}/><span title={p.path}>{p.verified?'●':'○'} {p.path.split('/').pop()}:{p.line} {p.condition} {p.hitCondition} {p.logMessage}</span></label>{p.message&&<small>{p.message}</small>}<button disabled={debug.busy} onClick={()=>debug.toggle(p.path,p.line)}>Remove</button></div>)}</details>
 {debug.threads.length>0&&<label>Thread<select value={debug.thread??''} disabled={debug.phase!=='paused'} onChange={e=>call(()=>debug.selectThread(Number(e.target.value)))}>{debug.threads.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 {debug.phase==='paused'&&<><h3>Call stack</h3>{debug.frames.map(f=><button className="debug-frame" key={f.id} aria-pressed={f.id===debug.frame?.id} onClick={()=>call(()=>debug.selectFrame(f))}>{f.name} · {f.source?.name??f.source?.path}:{f.line}</button>)}<h3>Variables</h3>{debug.scopes.map(s=><details key={s.variablesReference}><summary>{s.name}{s.expensive?' (expensive)':''}</summary><VariableTree reference={s.variablesReference} debug={debug}/></details>)}<form onSubmit={e=>{e.preventDefault();call(()=>debug.evaluate(expression,'repl'));}}><label>Evaluate expression<input value={expression} onChange={e=>setExpression(e.target.value)}/></label><button disabled={!expression.trim()}>Evaluate</button><button type="button" disabled={!expression.trim()} onClick={()=>setWatch(expression)}>Watch on each pause</button>{watch&&<button type="button" onClick={()=>setWatch('')}>Clear watch</button>}<pre>{debug.evaluation}</pre></form></>}
 <details open><summary>Debug output</summary><OutputLog label="Debug output" className="debug-output">{debug.output||'Program output appears here.'}</OutputLog></details>
 </aside>;
}
