import * as monaco from 'monaco-editor';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import type { ConnectedServer } from './languageServices';
const range=(r:any)=>new monaco.Range(r.start.line+1,r.start.character+1,r.end.line+1,r.end.character+1);
const lspRange=(r:monaco.IRange)=>({start:{line:r.startLineNumber-1,character:r.startColumn-1},end:{line:r.endLineNumber-1,character:r.endColumn-1}});
export function connectModel(editor:monaco.editor.IStandaloneCodeEditor,path:string,server:ConnectedServer,onNavigate:(path:string,line:number)=>void,onError:(text:string)=>void){
 const model=editor.getModel();if(!model)return ()=>{};
 const uri=monaco.Uri.file(path).toString();const disposables:monaco.IDisposable[]=[];let disposed=false;let version=1;
 const notify=(method:string,params:unknown)=>invoke('lsp_notify',{session:server.id,method,params});
 let sync=notify('textDocument/didOpen',{textDocument:{uri,languageId:model.getLanguageId(),version,text:model.getValue()}}).catch(e=>onError(String(e)));
 const request=async(method:string,params:unknown)=>{await sync;if(disposed)return null;return invoke<any>('lsp_request',{session:server.id,method,params});};
 const parameters=(position:monaco.Position)=>({textDocument:{uri},position:{line:position.lineNumber-1,character:position.column-1}});
 const onSave=(event:Event)=>{const detail=(event as CustomEvent<{path:string;text:string}>).detail;if(detail.path===path)sync=sync.then(()=>notify('textDocument/didSave',{textDocument:{uri},text:detail.text})).catch(e=>onError(String(e)));};
 window.addEventListener('afteredit:saved',onSave);disposables.push({dispose:()=>window.removeEventListener('afteredit:saved',onSave)});
 const syncKind=typeof server.capabilities.textDocumentSync==='number'?server.capabilities.textDocumentSync:server.capabilities.textDocumentSync?.change;
 disposables.push(model.onDidChangeContent(event=>{const current=++version;const changes=syncKind===2?event.changes.map(c=>({range:lspRange(c.range),text:c.text})):[{text:model.getValue()}];sync=sync.then(()=>notify('textDocument/didChange',{textDocument:{uri,version:current},contentChanges:changes})).catch(e=>onError(String(e)));}));
 void listen<any>('lsp:notification',e=>{
  if(disposed||e.payload.session!==server.id)return;
  const message=e.payload.message;
  if(message.method==='afteredit/stopped'){onError(`${server.language} server stopped`);monaco.editor.setModelMarkers(model,`lsp-${server.id}`,[]);return;}
  if(message.method!=='textDocument/publishDiagnostics'||message.params?.uri!==uri)return;
  if(message.params.version!==undefined&&message.params.version<version)return;
  monaco.editor.setModelMarkers(model,`lsp-${server.id}`,(message.params.diagnostics??[]).map((d:any)=>({...range(d.range),message:d.message,severity:[monaco.MarkerSeverity.Error,monaco.MarkerSeverity.Warning,monaco.MarkerSeverity.Info,monaco.MarkerSeverity.Hint][(d.severity??1)-1]??monaco.MarkerSeverity.Info,source:d.source})));
 }).then(off=>{if(disposed)off();else disposables.push({dispose:off});}).catch(e=>onError(String(e)));
 if(server.capabilities.hoverProvider)disposables.push(monaco.languages.registerHoverProvider(server.language,{async provideHover(candidate,position){if(candidate!==model)return null;try{const data=await request('textDocument/hover',parameters(position));if(!data)return null;const contents=(Array.isArray(data.contents)?data.contents:[data.contents]).filter(Boolean).map((c:any)=>({value:typeof c==='string'?c:c.language?`\`\`\`${c.language}\n${c.value}\n\`\`\``:c.value,isTrusted:false}));return {contents,range:data.range?range(data.range):undefined};}catch(e){onError(String(e));return null;}}}));
 if(server.capabilities.completionProvider)disposables.push(monaco.languages.registerCompletionItemProvider(server.language,{triggerCharacters:server.capabilities.completionProvider.triggerCharacters,async provideCompletionItems(candidate,position){if(candidate!==model)return {suggestions:[]};try{const data=await request('textDocument/completion',parameters(position));const items=Array.isArray(data)?data:data?.items??[];const word=model.getWordUntilPosition(position);return {suggestions:items.map((item:any)=>({label:item.label,kind:monaco.languages.CompletionItemKind.Text,detail:item.detail,documentation:typeof item.documentation==='string'?item.documentation:item.documentation?.value,insertText:item.textEdit?.newText??item.insertText??item.label,insertTextRules:item.insertTextFormat===2?monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet:undefined,range:item.textEdit?.range?range(item.textEdit.range):item.textEdit?.insert?range(item.textEdit.insert):new monaco.Range(position.lineNumber,word.startColumn,position.lineNumber,word.endColumn),additionalTextEdits:item.additionalTextEdits?.map((e:any)=>({range:range(e.range),text:e.newText}))}))};}catch(e){onError(String(e));return {suggestions:[]};}}}));
 if(server.capabilities.definitionProvider){disposables.push(monaco.languages.registerDefinitionProvider(server.language,{async provideDefinition(candidate,position){if(candidate!==model)return null;try{const data=await request('textDocument/definition',parameters(position));return (Array.isArray(data)?data:data?[data]:[]).map((loc:any)=>({uri:monaco.Uri.parse(loc.uri??loc.targetUri),range:range(loc.range??loc.targetSelectionRange)}));}catch(e){onError(String(e));return null;}}}));disposables.push(monaco.editor.registerEditorOpener({openCodeEditor(_source,resource,selection){if(resource.scheme!=='file')return false;const line=selection&&'startLineNumber'in selection?selection.startLineNumber:selection&&'lineNumber'in selection?selection.lineNumber:1;onNavigate(resource.fsPath,line);return true;}}));}
 if(server.capabilities.documentFormattingProvider)disposables.push(monaco.languages.registerDocumentFormattingEditProvider(server.language,{async provideDocumentFormattingEdits(candidate,options){if(candidate!==model)return [];try{const edits=await request('textDocument/formatting',{textDocument:{uri},options});return (edits??[]).map((e:any)=>({range:range(e.range),text:e.newText}));}catch(e){onError(String(e));return [];}}}));
 return ()=>{disposed=true;disposables.forEach(d=>d.dispose());monaco.editor.setModelMarkers(model,`lsp-${server.id}`,[]);void sync.then(()=>notify('textDocument/didClose',{textDocument:{uri}})).catch(()=>{});};
}
